<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
    <RootNamespace>PHARMA.Services</RootNamespace>
    <AssemblyName>PHARMA.Services</AssemblyName>
    <LangVersion>5</LangVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PHARMA.DataAccess\PHARMA.DataAccess.csproj" />
    <ProjectReference Include="..\PHARMA.Models\PHARMA.Models.csproj" />
    <ProjectReference Include="..\PHARMA.Common\PHARMA.Common.csproj" />
  </ItemGroup>
</Project>
