<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
    <RootNamespace>PHARMA.Common</RootNamespace>
    <AssemblyName>PHARMA.Common</AssemblyName>
    <LangVersion>5</LangVersion>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>
</Project>
